CREATE DATABASE BADMOVIES;

USE BADMOVIES;

CREATE TABLE IF NOT EXISTS GENRES(
    id INT NOT NULL AUTO_INCREMENT,
    genre VARCHAR(500) NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS FAVORITES(
    id INT NOT NULL AUTO_INCREMENT,
    movie_id INT NOT NULL,
    PRIMARY KEY(id)
);